### ISSUE TITLE
[ERROR] Error loading vanilla ASM: `ClassNotFoundException: ge`

### ISSUE THREAD

**Issue by Krutoy242** [Project-RT/RandomTweaker#69]
Loading game with RandomTweaker i found this error appear in debug.log file:

```less
[main/ERROR] [ink.ikx.rt.classTransforms.RandomTweakerClassTransformer]: Error loading vanilla ASM
java.lang.RuntimeException: java.lang.ClassNotFoundException: ge
	at ink.ikx.rt.classTransforms.RandomTweakerClassWriter.getCommonSuperClass(RandomTweakerClassWriter.java:19) ~[RandomTweakerClassWriter.class:?]
	at org.objectweb.asm.ClassWriter.getMergedType(ClassWriter.java:1698) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.Frame.merge(Frame.java:1530) ~[asm-debug-all-5.2.jar:5.2]
  [...]
```

What does this error means? Does this means some of RandomTweaker functionality not working?

**Comment by ikexing-cn** [comment]
Ignore it

**Comment by Krutoy242** [comment]
Ok, i will ignore it.

But i would like if ignorable or errors that have no relay on mod features marked as "WARN" instead of "ERROR" or even "INFO" log level 😊

**Comment by ikexing-cn** [comment]
Thank you for your suggestion
