### ISSUE TITLE
`1.4.6` Crash: `UnsatisfiedLinkError: 'long org.lwjgl.opengl.CallbackUtil.ncreateGlobalRef(java.lang.Object)'`

### ISSUE THREAD

**Issue by Krutoy242** [Project-RT/RandomTweaker#82]
Launching game with a version `1.4.6` causing crash:

```ruby
java.lang.UnsatisfiedLinkError: 'long org.lwjgl.opengl.CallbackUtil.ncreateGlobalRef(java.lang.Object)'
at org.lwjgl.opengl.CallbackUtil.ncreateGlobalRef(Native Method)
at org.lwjgl.opengl.CallbackUtil.createGlobalRef(CallbackUtil.java:61)
at org.lwjgl.opengl.GL43.glDebugMessageCallback(GL43.java:304)
at meldexun.renderlib.opengl.debug.OpenGLDebugMode$1.enable(OpenGLDebugMode.java:26)
at meldexun.renderlib.opengl.debug.OpenGLDebugMode.setupDebugOutput(OpenGLDebugMode.java:350)
at net.minecraft.client.Minecraft.handler$zei000$init_finishMinecraftLoading(MinecraftAccessor.java:5358)
at net.minecraft.client.Minecraft.init(MinecraftAccessor.java:535)
```

## https://mclo.gs/eYDZLxY

This crash does not happen on `1.4.5`.

**Comment by ikexing-cn** [comment]
Sorry for the late response. I’d like to know if this issue still exists in version 1.4.7?

**Comment by Krutoy242** [comment]
No, i cant reproduce it now. But this probably since I updated or changed other mods. Anyway, seems like issue can be closed.
